### ISSUE TITLE
Uncaught Error: Class 'mysqli' not found

### ISSUE THREAD

**Issue by kha7iq** [jareer12/PasteSite#2]
Accessing the service via browser returns the following error

```bash
❯ curl localhost:8080
<!DOCTYPE html>
<html lang="en">

<!-- Styles, Scripts & Metas -->

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="./_styles/tailwinds.css">
    <link rel="stylesheet" href="./_styles/index.css">
    <link rel="stylesheet" href="./_styles/prism.css">
    <link rel="icon" href="./_styles/favicon.png">
    <title>PasteSite - Create New Paste</title>
    <meta charset="UTF-8">
</head>

<br />
<b>Fatal error</b>:  Uncaught Error: Class 'mysqli' not found in /var/www/html/database.php:8
Stack trace:
#0 /var/www/html/index.php(18): require_once()
#1 {main}
  thrown in <b>/var/www/html/database.php</b> on line <b>8</b><br />
```

Another issue is with the latest inclusion of `.env` feature, when .env file is not available it throws the following error even though the variables are already exported to  environment. 
It should first look for the `.env` file and if its not present then simply move forward as you are already looking for variables with `getenv`. 
To test this if you comment out [line 6](https://github.com/jareer12/PasteSite/blob/main/database.php#L6) it actually get the values passed via variables when launching the service. 
```bash
<br />
<b>Fatal error</b>:  Uncaught InvalidArgumentException: /var/www/html/.env does not exist in /var/www/html/dotenv.php:18
Stack trace:
#0 /var/www/html/database.php(6): DevCoder\DotEnv-&gt;__construct('/var/www/html/....')
#1 /var/www/html/index.php(18): require_once('/var/www/html/d...')
#2 {main}
  thrown in <b>/var/www/html/dotenv.php</b> on line <b>18</b><br />
```

To reproduce this locally you can use the following docker-compose
1. Create `docker-compose.yml` file with following content.
```yaml
version: "3.3"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        image: php:7-fpm
        depends_on:
          - db
        environment:
          MYSQL_HOSTNAME: "db"
          MYSQL_USERNAME: "root"
          MYSQL_PASSWORD: "testpass"
          MYSQL_DATABASE: "pastesite"
        volumes:
            - ./src:/var/www/html
    db:
        image: mysql:8.0.28
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "testpass"
            MYSQL_DATABASE: pastesite
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
```
3.  Create nginx config file `default.conf`.
```bash
server {
    index index.php index.html;
    server_name phpfpm.local;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

5.  Create a folder `src` and copy all your code inside this folder.
6.  docker-compose up
7.  `curl localhost:8080` or open it via web browser.
